version: '3.9'

volumes:
    init-db:
    data-db:

services:
    mongodb:
        image: mongo:5.0
        restart: always
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
            - ./data-db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongoadmin
            MONGO_INITDB_DATABASE: link_collector
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

    web:
        image: app
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/link_collector
        ports:
            - 8000:8000
        links:
            - mongodb
        depends_on:
            - migration

    migration:
        build: .
        image: app
        command: python manage.py migrate
        volumes:
            - .:/link_collector
        links:
            - mongodb
        depends_on:
            - make_migrations

    make_migrations:
        build: .
        image: app
        command: python manage.py makemigrations
        volumes:
            - .:/link_collector
        links:
            - mongodb
        depends_on:
            - mongodb
